name: Large Tests
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install Java Development Kit 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build & Run small tests
      run: ./build.sh build

    - name: Run large tests
      run: ./build.sh large-tests
